print("----Bienvenido Usuario----")
print("")
print("Mi nombre es Ronaldo Emilio Méndez Mayorga")
print("Mi carnet es 1563224")
print("")
print("Universidad Rafael Landivar - Campus San Alberto Hurtado")
print("Su fundación en 1963 en Quetzaltenango")
print("!Es la mejor universidad en Occidente !")